### PR TITLE
Initial inclusion of calamares

### PR DESCRIPTION
**Pull request by EbonJaeger**
### Summary

All of the work in here so far except the branding was done by Joey. Thanks, Joey!

### Test Plan

Install Solus in a VM on my Intel CPU/AMD GPU system

### Checklist

- [x] Package was built and tested against unstable

### CODE REVIEW

**Comment by EbonJaeger** [comment]
We should think about the size of our boot partition. The size of the kernel keeps getting larger and larger, and I'm thinking that maybe we should follow EndeavourOS and start using a 1GB boot partition by default.

**Comment by ReillyBrogan** [comment]
Agreed on a 1GB boot partition being the default. With modern SSD sizes being what they are 1GB should be reasonably small compared to the overall drive size.

**Comment by joebonrichie** [comment]
If there is a way to trivially check for a disk size of <=64GB (Chromebooks) then the boot partition size should still be 512MiB imho.

**Comment by silkeh** [comment]
Please reopen this PR against [getsolus/packages](https://github.com/getsolus/packages). Thanks!

**Pull request closed without merging**
